### ISSUE TITLE
protect Widgets integrations

### ISSUE THREAD

**Issue by TomTheRock** [joubertredrat/Matomo-ProtectTrackID#10]
Would be cool if this also provides protection on the widget embedded code 
Platform => Widgets
https://github.com/joubertredrat/Piwik-ProtectTrackID
<iframe src="http://www.xxxxx.com/piwik/index.php?module=Widgetize&action=iframe&moduleToWidgetize=Dashboard&actionToWidgetize=index&idSite=XXXXXXXXXXXXXXXXX&period=week&date=yesterday" frameborder="0" marginheight="0" marginwidth="0" width="100%" height="100%"></iframe>

**Comment by joubertredrat** [comment]
Hi @TomTheRock 

Thanks for this request, I will provide this on new plugin release.
