### ISSUE TITLE
Not displaying the tracking code

### ISSUE THREAD

**Issue by smartin77** [joubertredrat/Matomo-ProtectTrackID#11]
With version 3.2.0 tracking code area is empty same as tracking image.
Installed via downloading and activating via UI enabling.
Also there are too poorly described back-end. I'm not aware if there should be new site column or new table with foreign keys.

see: https://i.imgur.com/HWNkobp.jpg

**Comment by smartin77** [comment]
OK, when I add more characters (alphabet must contain at least 16 unique characters) there are tracking code displayed.
There should be added warning or validation error or some description in documentation about this.

**Comment by smartin77** [comment]
sorry this explained: Why JavaScript Tracking Code and Image Tracking Link is blank?

**Comment by joubertredrat** [comment]
hi @smartin77 

Without problem, if you have more questions, you are welcome.

Thanks.
