### ISSUE TITLE
Unable to change Hash string size

### ISSUE THREAD

**Issue by smartin77** [joubertredrat/Matomo-ProtectTrackID#12]
I tried 10 first time. And later I tried to change it to 36. Unable to do this via UI. I still got 10.

**Comment by joubertredrat** [comment]
Hi @smartin77,

I will investigate this issue. Thanks for reporting.

**Comment by smartin77** [comment]
Meanwhile Hash string size can be changed in table 'piwik_plugin_setting.setting_name=ProtectTrackID' and 'piwik_plugin_setting.setting_name' = 'lengthSetting' and 'piwik_plugin_setting.setting_value = {YOUR DESIRED VALLUE}'

**Comment by joubertredrat** [comment]
Hi @smartin77, sorry for a big delay in my response. I tried here and wasn't possible to reproduce the issue.

* I defined length to 36 and matomo doesn't accepted because and is between 5 and 25.
* I defined to 12 and after changed to 20 and worked fine.
