### ISSUE TITLE
Broken with Matomo 4.x

### ISSUE THREAD

**Issue by KZeni** [joubertredrat/Matomo-ProtectTrackID#14]
The plugin is no longer available to activate on Matomo 4, but even editing the plugin.json to have require => piwik set to `>=4.0.0-b1,<5.0.0-b1` (making the plugin able to be activated on Matomo 4.x) still has the normal numeric IDs being used for tracking.

As such, any property using this plugin previously no longer resolves properly and data isn't being recorded properly.

I had this being used for numerous sites so it's important to have this working as it did previously to avoid needing to update the tracking code for all of the sites to go back to unprotected site IDs.

**Comment by KZeni** [comment]
### Update
It seems to be working for the noscript image ID while the JavaScript ID isn't working.

**Comment by KZeni** [comment]
Please turn to https://github.com/joubertredrat/Piwik-ProtectTrackID/pull/15 for what appears to be a fix for Matomo 4 support.

**Comment by KZeni** [comment]
While https://github.com/joubertredrat/Piwik-ProtectTrackID/pull/15 has been merged, please see https://github.com/joubertredrat/Piwik-ProtectTrackID/issues/16#issuecomment-769463809 when it comes to getting this plugin updated on the official plugin directory.

**Comment by joubertredrat** [comment]
Hi guys, sorry for a big delay to update this plugin, but is here. https://plugins.matomo.org/ProtectTrackID
