### ISSUE TITLE
Matomo-ProtectTrackID is not supporting in matomo 4.X version

### ISSUE THREAD

**Issue by sampathboddula** [joubertredrat/Matomo-ProtectTrackID#18]
Hi @joubertredrat,
The latest version of Matomo 4.X ‘ProtectTrackID’ is not supporting and we using ‘ProtectTrackID’ many of the sites to track visits. Could you please tell us when you will start support ‘ProtectTrackID’ ?

Thanks
Sampath

**Comment by joubertredrat** [comment]
Hi @sampathboddula,

Thanks for use this plugin. I published new version of plugin at https://plugins.matomo.org/ProtectTrackID

Before update do backup.
