### ISSUE TITLE
vendor/hashids v1.0 does not support php8

### ISSUE THREAD

**Issue by w41l** [joubertredrat/Matomo-ProtectTrackID#23]
Bundled version of hashids (v1.0) thrown an error when using php8 
```[02-Dec-2021 02:34:24 UTC] PHP Deprecated:  Implicit conversion from float 21.5 to int loses precision in /var/www/matomo/plugins/ProtectTrackID/vendor/hashids/hashids/lib/Hashids/Hashids.php on line 225```

Latest version of [hashids already support php8](https://github.com/vinkla/hashids/releases/tag/4.1.0)

**Comment by joubertredrat** [comment]
Hi @w41l, sorry for a big delay in my response. I updated all dependencies to support PHP 8 in version 2.0.1 of plugin
