### ISSUE TITLE
Accidental drop of PHP7.4 support due to ramsey/uuid update

### ISSUE THREAD

**Issue by JanThiel** [joubertredrat/Matomo-ProtectTrackID#27]
Hey there,

your latest released dropped support for PHP7.4 by defining PHP8 a requirement in your composer.json.
Yes PHP7.4 is EOL but as Matomo still supports it you cannot assume there are no more PHP7 installations out in the wild.

Updating your plugin to 2.1 on PHP7.4 would break the Matomo installation and prevents tracking at all.

Please roll back this requirement and only introduce breaking changes like this in a major version update (2.0 => 3.0).

Thank you very much.

**Comment by JanThiel** [comment]
So sorry! Screw that ... our dev Matomo on PHP 7.4 (one of several version for backward compat testing) sent us in the wrong direction and pointed out your plugin as the one being last updated before the issue was introduced. We will have to check were the dependency is actually comming from. It's obviously NOT your composer.json...

**Comment by JanThiel** [comment]
Ok, I have to revert the close. It IS your Plugin. But I believe you just didn't notice :-)

One of your dependencies dropped PHP7 support:

**PHP7 + 8**
https://packagist.org/packages/ramsey/uuid#4.2.3

**PHP 8**
https://packagist.org/packages/ramsey/uuid#4.3.0

You introduced 4.6.0.
https://packagist.org/packages/ramsey/uuid#4.6.0

So composer requires PHP8 for your plugin now.

Please downgrade ramsey/uuid to 4.2.3 for now.

**Comment by joubertredrat** [comment]
Hi @JanThiel, thanks for your issue, I'm doing investigation here.

**Comment by joubertredrat** [comment]
Hi @JanThiel, I tested here with PHP 8.1 and worked, but I want to double check to see if it's working on PHP 7.4. Could you check in your environment if will works? Thanks

**Comment by JanThiel** [comment]
Good Morning @joubertredrat 

The fix looks good to me. Thanks you very much for your quick response.
I just double checked your update and checking against the composer plattform_check.php:

https://github.com/joubertredrat/Matomo-ProtectTrackID/blob/fix-uuid-dependency/vendor/composer/platform_check.php#L7-L9

Min version is now PHP 7.3.5

👍

**Comment by joubertredrat** [comment]
Hi @JanThiel, the plugin with fix was released.

https://github.com/joubertredrat/Matomo-ProtectTrackID/releases/tag/2.1.1
https://plugins.matomo.org/ProtectTrackID

Thanks again for your issue
