### ISSUE TITLE
Site domain instead hash

### ISSUE THREAD

**Issue by borodatt** [joubertredrat/Matomo-ProtectTrackID#3]
Hi!
Is it possible to add into the plugin ability to use site domain instead of a hash?
Ready to fund this feature:)

**Comment by joubertredrat** [comment]
hi @borodatt 

Thanks for use my plugin. I'm developing another plugin that will possible to create custom trackers as user define, then you will create your custom tracker as you want.

Repo for this plugin is on https://github.com/joubertredrat/Piwik-CustomTrackID
