### ISSUE TITLE
Typed properties and nullable properties not supported on the Matomo-supported PHP version

### ISSUE THREAD

**Issue by mwithheld** [joubertredrat/Matomo-ProtectTrackID#34]
According to the docs https://matomo.org/faq/on-premise/matomo-requirements/ Matomo 4.x supports PHP version 7.2.5 or greater, but ProtectTrackerID version 2.3.0 contains some code not compatible with this PHP version at

https://github.com/joubertredrat/Matomo-ProtectTrackID/blob/master/PluginSettings.php#L29

URL: 
/index.php?module=CoreAdminHome&action=generalSettings&idSite=1&period=day&date=yesterday

Log message:
PHP Parse error:  syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in /home1l/urchin/www/plugins/ProtectTrackID/PluginSettings.php on line 29

This causes the app to die, so a fix would be much appreciated!  We can't upgrade PHP bc our enterprise is dependent on RedHat Software Collections' PHP, which is sticking to old PHP.

Typed properties and nullable properties were not introduced until PHP 7.4 (ref https://php.watch/versions/7.4/typed-properties).

**Comment by joubertredrat** [comment]
Hi @mwithheld, thanks for your issue. 

You're right, I'm going to create fix here, thanks.

**Comment by joubertredrat** [comment]
Hi @mwithheld, can you provide de exaclty version of PHP are you using?

**Comment by mwithheld** [comment]
PHP 7.3.20

**Comment by joubertredrat** [comment]
@mwithheld I published version 2.4.0. Feel free to update and check it. If issue persist, you can reopen this task.
