### ISSUE TITLE
BC Math/GMP not compatible with Matomo 4.x requirements

### ISSUE THREAD

**Issue by mwithheld** [joubertredrat/Matomo-ProtectTrackID#38]
ProtectTrackID 2.5.0 on PHP 7.3.x throws this error on our server:

```
Uncaught exception in API: plugins/ProtectTrackID/vendor/hashids/hashids/src/Hashids.php(408): Missing BC Math or GMP extension. [Query: ?module=CoreHome&action=index&idSite=2&period=day&date=yesterday, CLI mode: 0]

access: "GET /index.php?module=CoreHome&action=index&idSite=2&period=day&date=yesterday HTTP/1.1" 500 1671 "-"
```

Matomo 4.14.1
PHP 7.3.20

The BC Math or GMP extensions are not part of the PHP extension requirements at 
https://matomo.org/faq/on-premise/matomo-requirements/

I suggest you 
EITHER 
Re-jig this plugin code to remove the dependency on these extensions
OR
* Improve the documentation for this module to make the PHP extension requirements clear and obvious
* Add a check for these extensions on install and execution and fail gracefully so it does not throw a 500 HTTP error

**Comment by joubertredrat** [comment]
Solved
