### ISSUE TITLE
Not compatible with Matomo 4.15.0 and could not be loaded: ProtectTrackID

### ISSUE THREAD

**Issue by mwithheld** [joubertredrat/Matomo-ProtectTrackID#42]
Hello!  This message has shown for the last couple of versions of Matomo:
`The following plugins are not compatible with Matomo 4.15.0 and could not be loaded: ProtectTrackID.`
Can you update?

**Comment by joubertredrat** [comment]
Hi @mwithheld, thanks for your report.

I'm using the version 4.15.0 without any issues. Is it possible to describe which steps you're doing to get this issue for me test in my environment?

**Comment by mwithheld** [comment]
Huh yeah if I manually install it I don't see the notice.  I think I need to figure out what's going my deploy script.  Sorry for the trouble.

**Comment by joubertredrat** [comment]
Hi @mwithheld. No worries about that, if you have more doubts, feel free to ask :)
