### ISSUE TITLE
Lenght should be Length

### ISSUE THREAD

**Issue by dynajoe** [joubertredrat/Matomo-ProtectTrackID#5]
The word is spelled wrong consistently. I'm worried a future update could break this. So fixing it sooner rather than later would be great!

**Comment by joubertredrat** [comment]
Hi @joeandaverde 
Thanks for repporting. I really don't understand why I invert "t" with "h" on Length, but I will provide fix for this and new version today or tomorow.

**Comment by joubertredrat** [comment]
Fixed on commit 91e34a4b844a546edafa32d9f914491dec7a128a
