### ISSUE TITLE
Piwik break when no hit yet

### ISSUE THREAD

**Issue by tkapler** [joubertredrat/Matomo-ProtectTrackID#7]
If you activate this plugin and there is yet no hit in the database, and try to login with non-global-admin login, the piwik breaks and throws 
An error occurred
You cannot read value of baseSetting setting of "ProtectTrackID" plugin
(or slightly different, i got it in my language).
It is not critical as it  is very unlikely situation

**Comment by joubertredrat** [comment]
Hi @tkapler 
Thanks for reports, are you using latest version of plugin? I will investigate this here.

**Comment by tkapler** [comment]
yes, the latest clean version of piwik (2.6.x) and the latest version clean version of Piwik-ProtectTrackID, tested yesterday.
When even a single hit to log db arrives, it works (or if the user is global admin, not just a single site admin or viewer), so it was not a big issue for me, i just wasn't able to find, where the problem is, as imo you are using standard SystemSetting getValue, so maybe it is not a problem of your plugin but in the core.

**Comment by joubertredrat** [comment]
Hi @tkapler 
I can reproduce this issue here, I will provide fix for this. Thanks again for your report.

**Comment by joubertredrat** [comment]
Hi @tkapler 
I solved this with this commit, https://github.com/joubertredrat/piwik/commit/3351ae04ed906ad541b73eca75fa0fb836f9da3b but Piwik is receiving PR now for new 3.x version, then I can't solve this problem to work with Piwik 2.x, but I will fix this on Piwik 3.x

**Comment by joubertredrat** [comment]
Hi @tkapler 
This issue will be solved on new Piwik and plugin major version. If you can test with Piwik 3.0.0-b1, you can clone with branch, https://github.com/joubertredrat/Piwik-ProtectTrackID/tree/dev-1.x
