### ISSUE TITLE
Piwik 3.0.1 compatibility

### ISSUE THREAD

**Issue by mfilotto** [joubertredrat/Matomo-ProtectTrackID#9]
Here is the message I get
Thanks for your help

> The following plugins are not compatible with Piwik 3.0.1 and could not be loaded: ProtectTrackID

**Comment by joubertredrat** [comment]
Hi @mfilotto 

This is strange, my piwik is on version 3.0.1 and plugin is running normally. But I will make various tests to see if I will found this problem.

In your case, was upgrade from version 2.X or was a new installation for 3.0.0 or 3.0.1?

Thanks for reporting.

**Comment by mfilotto** [comment]
@joubertredrat  It's a fresh new install

**Comment by joubertredrat** [comment]
> @joubertredrat It's a fresh new install

I will test here then, Thanks for reporting.

**Comment by joubertredrat** [comment]
Hi @mfilotto 

I tested here and worked without problems, as below. Can you provide a print with this error for me to see? Thanks.

![screenshot-0 0 0 0 8989-2017-02-24-14-08-40](https://cloud.githubusercontent.com/assets/1520407/23313140/3c6900ae-fa9b-11e6-8a5b-fccc4d8333be.png)

![screenshot-0 0 0 0 8989-2017-02-24-14-09-14](https://cloud.githubusercontent.com/assets/1520407/23313150/51929378-fa9b-11e6-82a2-64a6502b1f62.png)

![screenshot-0 0 0 0 8989-2017-02-24-14-09-48](https://cloud.githubusercontent.com/assets/1520407/23313159/59ce18f0-fa9b-11e6-979b-47d3762f10ca.png)

![screenshot-0 0 0 0 8989-2017-02-24-14-06-41](https://cloud.githubusercontent.com/assets/1520407/23313165/5d889a88-fa9b-11e6-9017-c50b4a521e9f.png)

![screenshot-0 0 0 0 8989-2017-02-24-14-10-34](https://cloud.githubusercontent.com/assets/1520407/23313166/60ee230a-fa9b-11e6-983e-c113b5f2dbc7.png)

**Comment by joubertredrat** [comment]
hi @mfilotto Can you install it?

**Comment by mfilotto** [comment]
@joubertredrat I'll try once more and let you know

**Comment by mfilotto** [comment]
Ok I've just tried once more and it's working just fine.
It was maybe just a debug message

**Comment by joubertredrat** [comment]
hi @mfilotto I hope to be helped. If want more questions, you can open new issue.

Regards
